import {
  AppWindow,
  ArrowDownUp,
  Bell,
  Braces,
  Calendar,
  Command,
  Database,
  Focus,
  GalleryHorizontal,
  Globe,
  Hand,
  History,
  Keyboard,
  Languages,
  LayoutDashboard,
  LayoutPanelTop,
  List,
  ListChecks,
  ListCollapse,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  Monitor,
  Palette,
  PanelLeft,
  Puzzle,
  Replace,
  Send,
  ShieldCheck,
  Timer,
  ToggleLeft,
} from "@lucide/astro/icons";

type PluginNavIcon = typeof Puzzle;

const PLUGIN_NAV_ICONS: Record<string, PluginNavIcon> = {
  overview: LayoutDashboard,
  theme: Palette,
  sidebar: PanelLeft,
  media: Monitor,
  scroll: ArrowDownUp,
  geo: MapPin,
  lang: Languages,
  env: Globe,
  transfer: Send,
  toggle: ToggleLeft,
  timer: Timer,
  child: Replace,
  toast: MessageSquare,
  attention: Focus,
  notify: Bell,
  calendar: Calendar,
  query: Database,
  "query-kit": Database,
  "json-api": Braces,
  overlay: LayoutPanelTop,
  permissions: ShieldCheck,
  dialog: AppWindow,
  menu: Menu,
  tooltip: MessageCircle,
  tabs: LayoutPanelTop,
  accordion: ListCollapse,
  command: Command,
  carousel: GalleryHorizontal,
  virtual: List,
  selection: ListChecks,
  keyboard: Keyboard,
  gesture: Hand,
  history: History,
};

export function getPluginNavIcon(id: string): PluginNavIcon {
  return PLUGIN_NAV_ICONS[id] ?? Puzzle;
}
